FROM debian:trixie-slim AS bun-install

ARG BUN_VERSION=latest

RUN apt-get update -qq \
  && apt-get install -qq --no-install-recommends \
    ca-certificates curl dirmngr gpg gpg-agent unzip \
  && apt-get clean && rm -rf /var/lib/apt/lists/* \
  && arch="$(dpkg --print-architecture)" \
  && case "${arch##*-}" in \
       amd64) build="x64-baseline";; \
       arm64) build="aarch64";; \
       *) echo "error: unsupported architecture: $arch"; exit 1 ;; \
     esac \
  && case "$BUN_VERSION" in \
       latest | canary | bun-v*) tag="$BUN_VERSION";; \
       v*) tag="bun-$BUN_VERSION";; \
       *) tag="bun-v$BUN_VERSION";; \
     esac \
  && case "$tag" in \
       latest) release="latest/download";; \
       *) release="download/$tag";; \
     esac \
  && curl "https://github.com/oven-sh/bun/releases/$release/bun-linux-$build.zip" \
       -fsSLO --compressed --retry 5 \
  && for key in "F3DCC08A8572C0749B3E18888EAB4D40A7B22B59"; do \
       gpg --batch --keyserver hkps://keys.openpgp.org --recv-keys "$key" \
       || gpg --batch --keyserver keyserver.ubuntu.com --recv-keys "$key"; \
     done \
  && curl "https://github.com/oven-sh/bun/releases/$release/SHASUMS256.txt.asc" \
       -fsSLO --compressed --retry 5 \
  && gpg --batch --decrypt --output SHASUMS256.txt SHASUMS256.txt.asc \
  && grep " bun-linux-$build.zip$" SHASUMS256.txt | sha256sum -c - \
  && unzip "bun-linux-$build.zip" \
  && mv "bun-linux-$build/bun" /usr/local/bin/bun \
  && chmod +x /usr/local/bin/bun


FROM bun-install AS deps
WORKDIR /app

RUN --mount=type=bind,source=package.json,target=package.json \
    --mount=type=bind,source=bun.lock,target=bun.lock \
    --mount=type=cache,target=/root/.bun \
    bun install --frozen-lockfile


FROM deps AS builder
WORKDIR /app
ENV NODE_ENV=production

COPY . .
RUN bun run build


FROM deps AS prod-deps
WORKDIR /app

RUN --mount=type=bind,source=package.json,target=package.json \
    --mount=type=bind,source=bun.lock,target=bun.lock \
    --mount=type=cache,target=/root/.bun \
    bun install --frozen-lockfile --production


################################
# TOOLS
################################
FROM public.ecr.aws/docker/library/busybox:stable-uclibc AS busybox


FROM gcr.io/distroless/base-nossl-debian13:nonroot AS runner

ARG BUN_RUNTIME_TRANSPILER_CACHE_PATH=0
ENV BUN_RUNTIME_TRANSPILER_CACHE_PATH=${BUN_RUNTIME_TRANSPILER_CACHE_PATH}
ENV BUN_INSTALL_BIN=/usr/local/bin

WORKDIR /app

COPY --from=busybox /bin/sh /bin/ls /bin/wget /bin/cat /bin/vi /bin/cp /bin/grep /bin/ln /bin/mkdir /bin/ps /bin/
COPY --from=bun-install /usr/local/bin/bun /usr/local/bin/bun
COPY --from=prod-deps /app/node_modules ./node_modules
COPY --from=builder /app/build ./build

ENV NODE_ENV=production
EXPOSE 3000

ENTRYPOINT ["/usr/local/bin/bun"]
CMD ["run", "node_modules/.bin/react-router-serve", "build/server/index.js"]